server:
  port: 9200
  context-path: /

spring:
  redis:
    host: edu.fbksy.org
    port: 6379
    password: 1qaz@WSX
    database: 0
  activiti:
    #启动时不检查流程文件
    check-process-definitions: false
    job-executor-activate: false
    #true表示使用历史表，如果不配置，则工程启动后可以检查数据库，只建立了17张表
    db-history-used: true
    #表示哪种情况下使用历史表，这里配置为full表示全部记录历史，方便绘制流程图
    history-level: full

    async-executor-enabled: false

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: pu3147
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5

  thymeleaf:
    cache: false
mybatis:
  #mapper-locations: classpath:cc/**/*Mapper.xml
  mapper-locations: classpath:mapping/*Mapper.xml