server:
  port: 8080
  context-path: /

spring:
  redis:
    host: edu.fbksy.org
    port: 6379
    password: 1qaz@WSX
    database: 0

  datasource:
    url: jdbc:mysql://edu.fbksy.org:3306/demo
    username: pu3147
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5

  thymeleaf:
    cache: false
mybatis:
  #mapper-locations: classpath:cc/**/*Mapper.xml
  mapper-locations: classpath:mapping/*Mapper.xml